# Dependencies

# Permalinks
permalink:        pretty

# Setup
title:            Directed Studies
tagline:          'Stratified Flow'
description:      ''
url:              http://jklymak.github.io/DirStu17/
baseurl:          '/DirStu17'

author:
  name:           'Jody Klymak'
  url:            http://web.uvic.ca/~jklymak

paginate:         5
paginate_path: "blog/page:num"

github:
  repo:           https://github.com/jklymak/Phy426
